### ISSUE TITLE
Hello Example Panics

### ISSUE THREAD

**Issue by KritR** [athena-org/phosphorus#3] opened 2015-04-25 18:19 UTC
I get the following error when trying to run the example `hello.rs`.

```
thread '<main>' panicked at 'Vertex(ShaderCompilationFailed("ERROR: 0:2: \'\' :  
version \'120\' is not supported\nERROR: 0:3: \'\' :  
#version required and missing.\nERROR: 0:4: \'attribute\' : 
syntax error: syntax error\n"))', src/render.rs:74
```

**Comment by LaylBongers** [comment] 2015-04-27 21:15
Sorry for the delay in resolving this, I'm looking at it now.

Edit: Meanwhile, could you give me the name of the GPU on the computer you got this panic on?
Edit 2: It could either be you don't have hardware acceleration for graphics, caused by no driver, or the driver isn't allowing this old a GLSL version. For the first, I can't do much, for the latter, I've got a fix ready, I just need to confirm it first.

**Comment by LaylBongers** [comment] 2015-04-28 00:24
Could you try if this branch fixes your problem: https://github.com/athena-org/phosphorus/tree/feature/show_text_blocks

**Comment by KritR** [comment] 2015-04-28 00:40
I tried that branch and it sadly did not fix anything.
Currently, I'm running a 2011 Mac Mini with an AMD Radeon HD 6630M .

**Comment by LaylBongers** [comment] 2015-04-28 20:56
After some help I've bumped the GLSL version to 1.50 core, the branch should work now, could you try again?

**Comment by KritR** [comment] 2015-04-29 22:42
Ok well now it's displaying this : 
![screen shot 2015-04-29 at 5 37 58 pm](https://cloud.githubusercontent.com/assets/6396099/7402996/f8e1e6e6-ee96-11e4-8523-711a86c024ac.png)
So not everything seems to be rendering.

**Comment by LaylBongers** [comment] 2015-04-30 07:42
This is correct, phosphorus has only existed for about 2 weeks. Rendering is extremely incomplete right now.

**Comment by LaylBongers** [comment] 2015-05-01 12:58
Closing this since the bug has been resolved, thanks for testing it on OSX, good to know these kind of bugs early on.

**Closed as completed by LaylBongers** 2015-05-01 12:58 UTC
